import { RawFolderContentType, FolderEntryType } from './index';

/**
 * Creates a mock folder with diverse children for testing the file explorer
 * Contains a mix of folders and files with various mime types
 */
export const createMockFolder = (): RawFolderContentType => {
  const now = new Date();
  const oneHourAgo = new Date(now.getTime() - 60 * 60 * 1000);
  const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const oneMonthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const children: FolderEntryType[] = [
    // Folders
    {
      id: 'folder_001',
      name: 'Documents This is A Super long folder name to test the UI awawawawawawawWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWawawaw',
      created: oneMonthAgo.toLocaleString(),
      modified: oneDayAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/Documents',
      type: 'folder',
      size: '0',
      mime: 'folder',
      modifiedTimeIso: oneDayAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 0,
      selected: false,
    },
    {
      id: 'folder_002',
      name: 'Photos',
      created: oneMonthAgo.toLocaleString(),
      modified: oneWeekAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/Photos',
      type: 'folder',
      size: '0',
      mime: 'folder',
      modifiedTimeIso: oneWeekAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 0,
      selected: false,
    },
    {
      id: 'folder_003',
      name: 'Videos',
      created: oneMonthAgo.toLocaleString(),
      modified: oneMonthAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/Videos',
      type: 'folder',
      size: '0',
      mime: 'folder',
      modifiedTimeIso: oneMonthAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 0,
      selected: false,
    },
    {
      id: 'folder_004',
      name: 'Projects',
      created: oneWeekAgo.toLocaleString(),
      modified: oneHourAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: true,
      sharedPasswordProtected: false,
      path: '/Projects',
      type: 'folder',
      size: '0',
      mime: 'folder',
      modifiedTimeIso: oneHourAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 0,
      selected: false,
    },
    {
      id: 'folder_005',
      name: 'Archives',
      created: oneMonthAgo.toLocaleString(),
      modified: oneMonthAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/Archives',
      type: 'folder',
      size: '0',
      mime: 'folder',
      modifiedTimeIso: oneMonthAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 0,
      selected: false,
    },

    // Text/Code files
    {
      id: 'file_001',
      name: 'notes.txt',
      created: oneDayAgo.toLocaleString(),
      modified: oneDayAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/notes.txt',
      type: 'file',
      size: '15.2 KiB',
      mime: 'text/plain',
      modifiedTimeIso: oneDayAgo.toISOString(),
      createdTimeIso: oneDayAgo.toISOString(),
      sizeBytes: 15565,
      selected: false,
    },
    {
      id: 'file_002',
      name: 'script.js',
      created: oneWeekAgo.toLocaleString(),
      modified: oneHourAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/script.js',
      type: 'file',
      size: '45.7 KiB',
      mime: 'application/javascript',
      modifiedTimeIso: oneHourAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 46797,
      selected: false,
    },
    {
      id: 'file_003',
      name: 'Documents This is A Super long file name to test the UI awawawawawawawawawaw',
      created: oneWeekAgo.toLocaleString(),
      modified: oneHourAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/styles.css',
      type: 'file',
      size: '2228.14 KiB',
      mime: 'text/css',
      modifiedTimeIso: oneHourAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 28774,
      selected: false,
    },
    {
      id: 'file_004',
      name: 'data.json',
      created: oneDayAgo.toLocaleString(),
      modified: oneHourAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/data.json',
      type: 'file',
      size: '102.4 KiB',
      mime: 'application/json',
      modifiedTimeIso: oneHourAgo.toISOString(),
      createdTimeIso: oneDayAgo.toISOString(),
      sizeBytes: 104858,
      selected: false,
    },
    {
      id: 'file_005',
      name: 'README.md',
      created: oneWeekAgo.toLocaleString(),
      modified: oneWeekAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/README.md',
      type: 'file',
      size: '8.3 KiB',
      mime: 'text/markdown',
      modifiedTimeIso: oneWeekAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 8499,
      selected: false,
    },

    // Image files
    {
      id: 'file_006',
      name: 'profile.jpg',
      created: oneMonthAgo.toLocaleString(),
      modified: oneMonthAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/profile.jpg',
      type: 'file',
      size: '320.5 KiB',
      mime: 'image/jpeg',
      modifiedTimeIso: oneMonthAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 328192,
      selected: false,
    },
    {
      id: 'file_007',
      name: 'icon.svg',
      created: oneWeekAgo.toLocaleString(),
      modified: oneWeekAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/icon.svg',
      type: 'file',
      size: '15.7 KiB',
      mime: 'image/svg+xml',
      modifiedTimeIso: oneWeekAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 16077,
      selected: false,
    },
    {
      id: 'file_008',
      name: 'banner.png',
      created: oneDayAgo.toLocaleString(),
      modified: oneDayAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/banner.png',
      type: 'file',
      size: '540.2 KiB',
      mime: 'image/png',
      modifiedTimeIso: oneDayAgo.toISOString(),
      createdTimeIso: oneDayAgo.toISOString(),
      sizeBytes: 553165,
      selected: false,
    },

    // Video files
    {
      id: 'file_009',
      name: 'presentation.mp4',
      created: oneMonthAgo.toLocaleString(),
      modified: oneWeekAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: true,
      path: '/presentation.mp4',
      type: 'file',
      size: '24.5 MiB',
      mime: 'video/mp4',
      modifiedTimeIso: oneWeekAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 25690112,
      selected: false,
    },
    {
      id: 'file_010',
      name: 'tutorial.mkv',
      created: oneWeekAgo.toLocaleString(),
      modified: oneWeekAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/tutorial.mkv',
      type: 'file',
      size: '75.8 MiB',
      mime: 'video/x-matroska',
      modifiedTimeIso: oneWeekAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 79458304,
      selected: false,
    },

    // Audio files
    {
      id: 'file_011',
      name: 'podcast.mp3',
      created: oneDayAgo.toLocaleString(),
      modified: oneHourAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/podcast.mp3',
      type: 'file',
      size: '15.3 MiB',
      mime: 'audio/mpeg',
      modifiedTimeIso: oneHourAgo.toISOString(),
      createdTimeIso: oneDayAgo.toISOString(),
      sizeBytes: 16039526,
      selected: false,
    },

    // PDF files
    {
      id: 'file_012',
      name: 'report.pdf',
      created: oneMonthAgo.toLocaleString(),
      modified: oneMonthAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/report.pdf',
      type: 'file',
      size: '2.1 MiB',
      mime: 'application/pdf',
      modifiedTimeIso: oneMonthAgo.toISOString(),
      createdTimeIso: oneMonthAgo.toISOString(),
      sizeBytes: 2201907,
      selected: false,
    },
    {
      id: 'file_013',
      name: 'contract.pdf',
      created: oneWeekAgo.toLocaleString(),
      modified: oneWeekAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/contract.pdf',
      type: 'file',
      size: '4.5 MiB',
      mime: 'application/pdf',
      modifiedTimeIso: oneWeekAgo.toISOString(),
      createdTimeIso: oneWeekAgo.toISOString(),
      sizeBytes: 4718592,
      selected: false,
    },

    // Document files
    {
      id: 'file_014',
      name: 'proposal.txt',
      created: oneDayAgo.toLocaleString(),
      modified: oneDayAgo.toLocaleString(),
      shared: false,
      sharedAllowAllRead: false,
      sharedAllowAllWrite: false,
      sharedPasswordProtected: false,
      path: '/proposal.txt',
      type: 'file',
      size: '25.7 KiB',
      mime: 'text/wysiwyg',
      modifiedTimeIso: oneDayAgo.toISOString(),
      createdTimeIso: oneDayAgo.toISOString(),
      sizeBytes: 26317,
      selected: false,
    },
    {
      id: 'file_015',
      name: 'meeting_notes.txt',
      created: oneHourAgo.toLocaleString(),
      modified: oneHourAgo.toLocaleString(),
      shared: true,
      sharedAllowAllRead: true,
      sharedAllowAllWrite: true,
      sharedPasswordProtected: false,
      path: '/meeting_notes.txt',
      type: 'file',
      size: '12.3 KiB',
      mime: 'text/document',
      modifiedTimeIso: oneHourAgo.toISOString(),
      createdTimeIso: oneHourAgo.toISOString(),
      sizeBytes: 12595,
      selected: false,
    },
  ];

  return {
    id: 'root_folder',
    name: 'Home',
    modified: now.toLocaleString(),
    created: oneMonthAgo.toLocaleString(),
    sharedAllowAllRead: false,
    sharedAllowAllWrite: false,
    sharedPasswordProtected: false,
    shared: false,
    parentId: '',
    path: '/',
    type: 'folder',
    children,
  };
};

// Export a ready-to-use mock folder
export const mockFolder = createMockFolder();
